import "server-only";

import { createOpenAPI } from "fumadocs-openapi/server";

import spec from "@/openapi/spec.json";

// The committed spec (generated by apps/server `scripts/gen-openapi.ts`) targets a self-hosted server. For
// the getairwave.tv reference we point the playground at a same-origin mock (so "Try it" works with example
// data and no real backend), and list the real self-host pattern as a second server people can switch to.
const doc = {
  ...(spec as Record<string, unknown>),
  servers: [
    { url: "/api/mock/public/v1", description: "Mock server — example data, no Airwave needed" },
    {
      url: "https://your-airwave-host/api/public/v1",
      description: "Your Airwave server — replace the host and use your API key",
    },
  ],
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const openapi = createOpenAPI({ input: { airwave: doc as any } });
